version: 2.1

jobs:
    build:
        working_directory: ~/code
        docker:
          - image: circleci/android:api-25-alpha
        steps:
          - checkout
          - restore_cache:
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          - run:
              name: "add x permission for gradlew as necessary"
              command: chmod +x ./gradlew
          - run:
              name: "download dependencies"
              command: "./gradlew androidDependencies --status"
          - run:
              name: "run lint test"
              command: "./gradlew lint test"
          - store_artifacts:
              path: app/build/reports
              destination: reports
          - save_cache:
              paths:
                - ~/.gradle
              key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
orbs:
    hello: circleci/hello-build@0.0.7 # uses the circleci/buildpack-deps Docker image

workflows:
    "Hello Workflow":
      jobs:
      #- hello/hello-build
      - build
